// Copyright 2019 Karl Stenerud
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
// IN THE SOFTWARE.

// Generated by github.com/kstenerud/go-concise-encoding/codegen
  // DO NOT EDIT
  // IF THIS LINE SHOWS UP IN THE GIT DIFF, THIS FILE HAS BEEN EDITED

package iterator

import (
	"github.com/kstenerud/go-concise-encoding/options"
)

// uint16

type uint16ArrayIterator struct{}

func newUint16ArrayIterator() ObjectIterator                                                { return &uint16ArrayIterator{} }
func (_this *uint16ArrayIterator) InitTemplate(_ FetchIterator)                             {}
func (_this *uint16ArrayIterator) NewInstance() ObjectIterator                              { return _this }
func (_this *uint16ArrayIterator) InitInstance(_ FetchIterator, _ *options.IteratorOptions) {}

type uint16SliceIterator struct{}

func newUint16SliceIterator() ObjectIterator                                                { return &uint16SliceIterator{} }
func (_this *uint16SliceIterator) InitTemplate(_ FetchIterator)                             {}
func (_this *uint16SliceIterator) NewInstance() ObjectIterator                              { return _this }
func (_this *uint16SliceIterator) InitInstance(_ FetchIterator, _ *options.IteratorOptions) {}

// uint8

type uint8ArrayIterator struct{}

func newUint8ArrayIterator() ObjectIterator                                                { return &uint8ArrayIterator{} }
func (_this *uint8ArrayIterator) InitTemplate(_ FetchIterator)                             {}
func (_this *uint8ArrayIterator) NewInstance() ObjectIterator                              { return _this }
func (_this *uint8ArrayIterator) InitInstance(_ FetchIterator, _ *options.IteratorOptions) {}

type uint8SliceIterator struct{}

func newUint8SliceIterator() ObjectIterator                                                { return &uint8SliceIterator{} }
func (_this *uint8SliceIterator) InitTemplate(_ FetchIterator)                             {}
func (_this *uint8SliceIterator) NewInstance() ObjectIterator                              { return _this }
func (_this *uint8SliceIterator) InitInstance(_ FetchIterator, _ *options.IteratorOptions) {}
